//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.18 at 10:18:47 AM IST 
//


package in.gov.uidai.authentication.uid_bfd_request._1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the in.gov.uidai.authentication.uid_bfd_request._1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Bfd_QNAME = new QName("http://www.uidai.gov.in/authentication/uid-bfd-request/1.0", "Bfd");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: in.gov.uidai.authentication.uid_bfd_request._1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Bfd }
     * 
     */
    public Bfd createBfd() {
        return new Bfd();
    }

    /**
     * Create an instance of {@link Skey }
     * 
     */
    public Skey createSkey() {
        return new Skey();
    }

    /**
     * Create an instance of {@link Bfd.Data }
     * 
     */
    public Bfd.Data createBfdData() {
        return new Bfd.Data();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Bfd }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.uidai.gov.in/authentication/uid-bfd-request/1.0", name = "Bfd")
    public JAXBElement<Bfd> createBfd(Bfd value) {
        return new JAXBElement<Bfd>(_Bfd_QNAME, Bfd.class, null, value);
    }

}
