//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.18 at 10:18:47 AM IST 
//


package in.gov.uidai.authentication.uid_auth_request_data._1;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the in.gov.uidai.authentication.uid_auth_request_data._1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: in.gov.uidai.authentication.uid_auth_request_data._1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Pid }
     * 
     */
    public Pid createPid() {
        return new Pid();
    }

    /**
     * Create an instance of {@link Demo }
     * 
     */
    public Demo createDemo() {
        return new Demo();
    }

    /**
     * Create an instance of {@link Bios }
     * 
     */
    public Bios createBios() {
        return new Bios();
    }

    /**
     * Create an instance of {@link Pv }
     * 
     */
    public Pv createPv() {
        return new Pv();
    }

    /**
     * Create an instance of {@link Pi }
     * 
     */
    public Pi createPi() {
        return new Pi();
    }

    /**
     * Create an instance of {@link Pa }
     * 
     */
    public Pa createPa() {
        return new Pa();
    }

    /**
     * Create an instance of {@link Pfa }
     * 
     */
    public Pfa createPfa() {
        return new Pfa();
    }

    /**
     * Create an instance of {@link Bio }
     * 
     */
    public Bio createBio() {
        return new Bio();
    }

}
